#' @title KNN : Predict
#' @description The function can be used to make prediction on test data using trained model
#' @param knnMdl a list containing:
#'  \itemize{
#'   \item knnMdl$data - The data set provided by user
#'   \item knnMdl$xCol - The column number of features provided by user or the best subset column number
#'   \item knnMdl$yCol - The column number of target provided by user
#'   \item knn$bestK - The best k nearest neighbor calculated using the function KnnFit
#'}
#'
#' @param testData a data frame or matrix, to compute the predictions
#'
#' @return a numeric / vector with prediction on test data using model generated by KnnFit
#' @export
#'
KnnPredict = function(knnMdl, testData){

  trainData = knnMdl$data
  xCol = knnMdl$xCol
  yCol = knnMdl$yCol
  bestK = knnMdl$bestK
  
  normalizedTrainData = trainData
  normalizedTestData = testData
  
  for (feature in xCol) {
    
    normalizedTrainData[, feature] = (trainData[, feature] - min(trainData[, feature])) / (max(trainData[, feature]) - min(trainData[, feature]))
    normalizedTestData[, feature] = (testData[, feature] - min(trainData[, feature])) / (max(trainData[, feature]) - min(trainData[, feature]))
  }

  prediction = FNN::knn.reg(normalizedTrainData[, xCol, drop =F], normalizedTestData[, xCol, drop = F], trainData[, yCol], k = bestK )

  return(prediction$pred)
}
