#' @title KNN : Predict
#' @description The function can be used to make prediction on test data using trained model
#' @param knnMdl a list containing:
#'  \itemize{
#'   \item knnMdl$data - The data set provided by user
#'   \item knnMdl$xCol - The column number of features provided by user or the best subset column number
#'   \item knnMdl$yCol - The column number of target provided by user
#'   \item knn$bestK - The best k nearest neighbor calculated using the function KnnFit
#'}
#'
#' @param testData a data frame or matrix, to compute the predictions
#'
#' @return a numeric / vector with prediction on test data using model generated by KnnFit
#' @export
#'
KnnPredict = function(knnMdl, testData){

  trainData = knnMdl$data
  xCol = knnMdl$xCol
  yCol = knnMdl$yCol
  bestK = knnMdl$bestK

  prediction = knn.reg(trainData[, xCol], testData[, xCol], trainData[, yCol], k = bestK )

  return(prediction)
}
